[package]
name = "lintab-core-daemon"
version = "0.1.0"
edition = "2021"
authors = ["Francisco Daniel Castro Borrome"]
license = "GPL-3.0-or-later"
description = "LinTab core daemon – virtual uinput tablet driver for Linux"

[[bin]]
name = "lintab"
path = "src/main.rs"

[dependencies]
tokio        = { version = "1",    features = ["full"] }
anyhow       = "1"
tracing      = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes        = "1"
clap         = { version = "4.4", features = ["derive"] }
mdns-sd      = "0.11"
serde        = { version = "1",   features = ["derive"] }
serde_json   = "1"
thiserror    = "1"
prost        = "0.12"
evdev        = "0.12"
local-ip-address = "0.6"
gethostname  = "0.4"

[build-dependencies]
prost-build = "0.12"

[profile.release]
opt-level = 3
lto = true
strip = true
